language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories: 
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
scripts:
  - nohub npm run start & 
  - sleep 3
  - npm run test