language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci 
  - PORT=3000
  - MONGO_URI=mongodb://127.0.0.1:27017/blog_ci
  - REDIS_URL=redis://127.0.0.1:6379
  - COOKIE_KEY=123123123
cache:
  directories: 
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
scripts:
  - nohub npm run start & 
  - sleep 3
  - npm run test