version: '3'

services:
  mongodb: 
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_data:/data/db
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  mongo_data: